apiVersion: lunchpail.io/v1alpha1
kind: Application
metadata:
  name: openroad-max-util
spec:
  api: workqueue
  role: worker
  tags: [EDA]
  command: python3 -u main.py
  description: >-
    Our goal is to find a maximum acheivable utilization for a given design.
  image: ghcr.io/lunchpail/openroad:0.3.5
  supportsGpu: true
  env:
    COPYIN_REPO: https://github.com/ieee-ceda-datc/aspdac-2022-tutorial/tree/main/part4-k8s-single-node-ray-demo/workspace
  code:
    - name: main.py
      source: |
{{ .Files.Get "src/main.py" | indent 8 }}

    - name: copy-templates.sh
      source: |
{{ .Files.Get "src/copy-templates.sh" | indent 8 }}
